language: python
python:
  - "3.7"
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - pytest --cov=nextcode/ --disable-warnings --junitxml=test-results/pytest.xml
after_success:
 - codecov